### ISSUE TITLE
Pergunta

### ISSUE THREAD

**Issue by Jarn40** [Fala-Impulser/backend#6]
Vocês tem algum plano em mente que falta ser desenvolvido? Alguma estrutura de rota e funcionalidades? Me interessei e gostaria de contribuir e como estou chegando agora para não bulinar antes de entender as necessidades resolvi perguntar!

Abraços!

**Comment by rafaelmenon** [comment]
Primeiramente muito obrigado pelo seu interesse em nosso projeto, sério é um agradecimento de coração mesmo. O projeto ainda está sendo construindo aos poucos, estamos definindo ainda algumas coisas então não temos nada 100% definido. Estamos fazendo o layout ainda para começarmos com o front. Mas fique a vontade para ideias e será muito bem vindo ao time. Assim que criarmos o front já com algumas coisas o projeto irá andar mais rápido e vai ficar claro para todos.
